### ISSUE TITLE
Observations.dwc api return 404 for pages over 334 

### ISSUE THREAD

**Issue by sadeghim** [inaturalist/iNaturalistAPI#125]
Hi,

I am harvesting Australian observations using the observations API and returns 404 for pages over 334 and it doesn't matter what page size I choose. Here are the api calls:

https://www.inaturalist.org/observations.dwc?page=334&max=10&place_id=6744
https://www.inaturalist.org/observations.dwc?page=334&max=100&place_id=6744
https://www.inaturalist.org/observations.dwc?page=334&max=200&place_id=6744

Could you please help?

**Comment by sadeghim** [comment]
To more clarify my use case: 

I get the number of entries using https://www.inaturalist.org/observations.json?place_id=6744 API and x-total-entries header field then calculate the number of pages by taking the page size into account.

if I call above url as json api instead of dwc (https://www.inaturalist.org/observations.json?page=334&max=10&place_id=6744)I will get following error:

`{
    "error": "Internal Server Error"
}`

**Comment by kueda** [comment]
Anything served from www.inaturalist.org is actually a concern for https://github.com/inaturalist/inaturalist, so please file an issue there if you think there's a bug. However, I strongly recommend you use the Node API instead of https://www.inaturalist.org/observations.dwc. It's much faster and more consistent. Docs are at http://api.inaturalist.org/v1/docs/
