### ISSUE TITLE
Feature request: Add additional observation formats provided by Rails API

### ISSUE THREAD

**Issue by JWCook** [inaturalist/iNaturalistAPI#240]
This isn't urgently important, but I thought it would be worth creating an issue for this since it's is one of the few useful features of the old API that isn't yet available in the new one.

In the original Rails-based API, [`GET /observations`](https://www.inaturalist.org/pages/api+reference#get-observations) offers some extra data formats in addition to JSON:
* atom
* csv
* dwc
* kml
* widget 

Of those 5 formats, the main two of interest for me are:
* **Darwin Core**: This one is quite handy, as it otherwise takes a bit of work client-side to convert observation JSON into DWC format. My current use case for this is writing it to XMP image metadata using the [`dwc` namespace](https://www.exiv2.org/tags-xmp-dwc.html).
* **CSV:** It's not difficult to convert JSON to CSV client-side, but it's a common enough use case that it would be useful to have. 

A related question: is there a timeline for retiring the old API? Let me know if that would be better asked as a separate issue on https://github.com/inaturalist/inaturalist.

**Comment by kueda** [comment]
I defer to @pleary on this, but I feel pretty strongly that the API should not deal in other formats, mainly because this node app is already quite complicated and support for XML output is just going to make that worse, in addition to committing ourselves to a long future of maintenance. More broadly, our API is mainly for our internal use, and we don't have any current need for these additional formats (I could imagine us having such a need if we could get the node app to generate CSV faster than the Rails app, where it is *really* slow).

> is there a timeline for retiring the old API?

Not at present. I have a vague feeling that if/when we can release the node API v2, we should announce deprecation of the Rails API (v0?) in 6 months and deprecation of v1 in 1 year... but v2 development is going very slowly so I'm not sure when it will be ready.

**Comment by JWCook** [comment]
Thanks for the response, that makes perfect sense.
