### ISSUE TITLE
How to use POST /observations?

### ISSUE THREAD

**Issue by JWCook** [inaturalist/iNaturalistAPI#257]
Could you point me to any docs or hints on what kind of request body is accepted by `PUT` and `POST /observations` (v1)? The Swagger spec contains a [PostObservation](https://github.com/inaturalist/iNaturalistAPI/blob/main/lib/views/swagger_v1.yml.ejs#L3472-L3483) schema, but it only shows species_guess, taxon_id, and description.

Thanks!

**Comment by kueda** [comment]
Ugh, sorry our docs are not that great. `POST https://api.inaturalist.org/v1/observations` should accept a JSON body with any of the parameters documented at https://www.inaturalist.org/pages/api+reference#post-observations (I guess you could call that API v0). Here's an example with cURL using an existing photo ID:

```
curl -XPOST 'https://api.inaturalist.org/v1/observations' \
  -H 'Accept: application/json' \
  -H 'Authorization: YOUR_JWT' \
  -H 'Content-Type: application/json' \
  --data-raw '{
    "observation":{
      "description":"This is the description",
      "latitude":37.8043514,
      "longitude":-122.2711639,
      "positional_accuracy":16422,
      "geoprivacy":"obscured",
      "place_guess":"Oakland, CA, USA",
      "observation_field_values_attributes":[],
      "tag_list":"India",
      "uuid":"53411fc2-bdf0-434e-afce-4dac33970173",
      "taxon_id":47157,
      "species_guess":"Butterflies and Moths",
      "observed_on_string":"2011/08/22 11:01 AM PDT"},
      "project_id":[],
      "local_photos":{"0":[129264544]}
    }'
```

The `uuid` might require some explanation: every obs gets a UUID, but the client can set it to prevent creating duplicates if there's no response to the POST request due to a lost connection. In that situation, the client might assume the obs was never created and try to POST it again. If the same UUID is used and the obs already exists, the server will treat the request as a PUT instead and update the existing record.

I do recommend you use https://api.inaturalist.org/v1, even if the docs are not great. The responses are more consistent across endpoints.

**Comment by JWCook** [comment]
Thanks for the quick response!

**Comment by JWCook** [comment]
@kueda Do the other v1 `POST` endpoints have the same "upsert" behavior?

**Comment by kueda** [comment]
`/v1/observation_photos` does, probably sounds and project obs too, but you might want to test that.
