### ISSUE TITLE
Add places/autocomplete to API v2

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistAPI#287]
For iNatRN, we'll need places autocomplete to work the same way it works for Explore on the web.

- [x] GET /places/autocomplete

**Comment by pleary** [comment]
For now this lives at GET `/places`, though we could also consider moving it to `/places/autocomplete` since it behaves similar to taxa autocomplete, which lives at `/taxa/autocomplete`. But taxa has a more advanced search endpoint at `/taxa`, and places doesn't have another such endpoint. I dunno - naming things is hard

**Comment by albullington** [comment]
Okay, using GET `/places`. It looks like that endpoint still needs a `fields` parameter enabled.

**Comment by pleary** [comment]
Maybe I hadn't deployed recent changes. The fields parameter appears to be working on this endpoint for me, e.g. https://stagingapi.inaturalist.org/v2/places?q=a&fields=name and:

```
curl -XPOST \
    -H "X-HTTP-Method-Override: GET" \
    -H "Content-Type: application/json" \
    -d '{"q":"a","fields": {"name": true}}' \
    "https://stagingapi.inaturalist.org/v2/places"
```
