### ISSUE TITLE
how does paging work in taxa and taxa/autocomplete endpoints? 

### ISSUE THREAD

**Issue by DeividZavala** [inaturalist/iNaturalistAPI#345]
I'm building an app in which I need to list the species that match a search parameter, according to the documentation the maximum number of items I can list for the taxa/autocomplete endpoint is 30 because some search terms return more than these 30 items, I need to implement pagination but I can't find the way to deal with this case or in default some alternative.

Thanks

**Comment by kueda** [comment]
First, these kinds of questions are better asked in the [Forum](https://forum.inaturalist.org/). We use Github issues for actionable work.

To your question, the [docs for /v1/taxa](https://api.inaturalist.org/v1/docs/#!/Taxa/get_taxa) say you can set `per_page` to 200, so that might meet your need. If not, that endpoint also supports the `id_above` (documented) and `order` / `order_by` params (not documented, but should be). So you can page through results like this:

https://api.inaturalist.org/v1/taxa?q=red&order_by=id&order=asc
https://api.inaturalist.org/v1/taxa?q=red&order_by=id&order=asc&id_above=2069 (where `2069` is the ID of the last result of the first request)

We also generate an export of our complete taxonomy every month (search for iNaturalist Taxonomy DarwinCore Archive" at https://www.inaturalist.org/pages/developers), if you don't need real-time results).
