### ISSUE TITLE
more stuff for the taxon endpoint

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#35]
We'll need more info for the new taxon page, namely:

- [x] ancestors
- [x] children
- [x] taxon names
- [x] conservation statuses
- [x] listed taxa / establishment means
- [x] at least 9 TaxonPhotos associated with this taxon and/or its descendants, including URL, attribution, and the taxon they're associated with (useful if it's a descendant)

**Comment by pleary** [comment]
Can you provide a little more detail about what you need? For ancestors/children would you need more than what details currently provides http://api.inaturalist.org/v1/taxa/12727 ? Seems like you'd minimally want scientific name, rank, and common name.

What about conservation statuses and establishment means? The API currently returns the best matching value of each when given a place. Do you need more than that? Do you need data about these across all places?

**Comment by kueda** [comment]
Definitely need sci name, common name, and rank for all ancestors and children.

For conservation statuses I need

* place.name
* status
* iucn
* url
* authority
* description

For establishment I need listed taxon

* place.name
* establishment_means
* list.title
* id (or again, enough info to link to the listed taxon

For ConservationStatus I need all of them associated with this taxon (not descendants or ancestors). For establishment and listed taxa... let's just stick with the requested place for now. I feel like we might get a better list of places if/when Scott's atlas idea pans out. In addition to what's already in the API, it might be nice to get the listed taxon's `list.title`, but not critical if it's a pain.

**Comment by pleary** [comment]
Do you only need the listed taxa with establishment means? Right now I have it returning all listed_taxa with a place or means (and not filtering by preferred_place_id)

**Comment by pleary** [comment]
I added the taxon photos, but didn't get the "taxon if descendant" bit in yet. The new code needs new data in ES, which is generated by a new rails branch. I indexed the first few thousand taxa on Staging and have the API running this branch there if you want to test it out

**Comment by kueda** [comment]
To more requests to help configure the map:

1) GBIF ID
2) Enough info to configure the taxonMap to show a range (I think this is just a boolean)

**Comment by pleary** [comment]
I turned `taxon.photos` into `taxon.taxon_photos` which now includes the taxon of the clade where the photo came from. Now that I think of it, I wonder how useful this will be since it's the taxon of the clade the photo is attached to, not the species featured in the photo. If it's not that useful, then maybe `taxon_photos` is overkill and we go back to `photos`.

I was thinking about doing the map stuff separately from taxon details. Right now it seems like we fetch GBIF IDs on demand, not in bulk on some schedule. There can also be good reasons to expire cached IDs and look them up again, and we probably don't want to do that for all taxa all the time. So that is the kind of thing we might want to fetch asynchronously when maps are rendered, not every time we return taxon details from the API. Maybe there's a separate taxon map layers API that the taxon map JS code can call and append the map layers menu accordingly.

**Comment by kueda** [comment]
I think the taxon photos stuff will still be useful. I'm happy to go with whatever seems the most reasonable to you regarding taxon map parameters. Happy to make another request if that seems cleaner to you.

**Comment by pleary** [comment]
pretty sure this is done now
