### ISSUE TITLE
obscured cartography not applying to observations of threatened taxa

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistAPI#5]
E.g. http://www.inaturalist.org/observations/339073 and its display at http://www.inaturalist.org/observations?utf8=%E2%9C%93&q=&search_on=&quality_grade=any&reviewed=&identifications=any&captive=&place_id=&swlat=36.74864635797473&swlng=-122.33892225585942&nelat=37.02324629220921&nelng=-121.89946913085942&taxon_name=&taxon_id=&day=&month=&year=&order_by=observations.id&order=desc&rank=&hrank=&lrank=&site=&tdate=&d1=&d2=&filters_open=false&view=map

![screen shot 2015-08-24 at 1 32 56 pm](https://cloud.githubusercontent.com/assets/22691/9451656/c99ac98c-4a64-11e5-95cf-e436f733032d.png)

I was able to fix this by changing https://github.com/inaturalist/iNaturalistAPI/blob/master/lib/inaturalist_map_styles.js#L105 to something like `[private_location > 0]` and including `private_location` in the fields retrieved from ES, but I couldn't figure out how to strip private_location out of the `.grid.json` responses.

**Comment by pleary** [comment]
This was fixed with the first two file changes in 3c90597 . It is not stripping private_location field out of the grid.json (it is obfuscating the data), but this is actually good because we need that information in the front end. What we need on the front end is some indicator of wether or not an observation is to be represented by a circle or flag marker. Since the tileserver has to check both geoprivacy and presence of private coordinates to make that determination, the front-end code needs the same information to make the exact same determination.

We could have some step in-between fetching the data from ES and rendering the .grid.json to create some kind of "is_obscured" boolean (alternatively we could add that to the ES index itself), but currently elasticmaps isn't set up to have any logic in between fetch results and rendering. So there are various things we can do, though I do worry a little about slowing down the tileserver with more logic. If we really wanted to change it, I'd vote for adding a field to ES which would make the logic clearer for both the tileserver styles and the UTFGrid interaction offsets.

**Comment by kueda** [comment]
I'm fine with the way we have it. Not ideal, but workable, and not revealing anything we shouldn't.
