### ISSUE TITLE
zeros in return_bounds=true

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistAPI#72]
http://api.inaturalist.org/v1/observations?taxon_id=120720&per_page=1&return_bounds=true

returns:
```
total_bounds: {
swlat: 0,
swlng: 0,
nelat: 48.29173003323376,
nelng: -114.05738635919988
}
```

and http://api.inaturalist.org/v1/observations?taxon_id=42220&per_page=1&return_bounds=true
returns:
```
total_bounds: {
swlat: 0,
swlng: -135.98853785544634,
nelat: 62.13262579869479,
nelng: 0
}
```

**Comment by pleary** [comment]
This is caused by observations at 0,0, like http://www.inaturalist.org/observations/2570586 . `total_bounds` is technically correct, but it's looking at all observations including the un-mappable ones. We could change it to only look at mappable observations, but I think the best approach might be for you to send `verifiable=true`. That's what we're doing on the taxon page for example.

Any preference @kueda? Do we change the behavior of `total_bounds`, and define it as always representing mappable obs, or just leave it up to the user to specify their own params and keep it representing the results of the search.

**Comment by alexshepard** [comment]
I can definitely send `verifiable=true`

**Comment by alexshepard** [comment]
closing this as `verifiable=true` on iOS works fine for now.
